services:
  node1:
    hostname: node1.vespanet
    image: vespaengine/vespa
    command: configserver,services
    healthcheck:
      test: curl http://localhost:19071/state/v1/health
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 8080:8080
      - 19071:19071
    environment:
      VESPA_CONFIGSERVERS: node1.vespanet
      VESPA_CONFIGSERVER_JVMARGS: "-Xms32M -Xmx128M"
      VESPA_CONFIGPROXY_JVMARGS: "-Xms32M -Xmx32M"
    volumes:
      - vespa-data:/opt/vespa/var
    networks:
      - vespa-net

volumes:
  vespa-data:

networks:
  vespa-net:
    driver: bridge